import * as attributes from "./config/attributes.mjs";
import * as progression from "./config/progression.mjs";
import * as combat from "./config/combat.mjs";
import * as resources from "./config/resources.mjs";
import * as equipment from "./config/equipment.mjs";
import * as strategic from "./config/strategic.mjs";
import * as enemies from "./config/enemies.mjs";

export const SYSTEM_ID = "deicide";

export const DEICIDE = {
  id: SYSTEM_ID,

  attributes: attributes.attributes,
  attributeIds: attributes.attributeIds,
  attributeBase: attributes.attributeBase,
  attributeBands: attributes.attributeBands,
  grades: attributes.grades,
  gradeOrder: attributes.gradeOrder,
  growthTenths: attributes.growthTenths,
  qualityGrades: attributes.qualityGrades,
  formulas: attributes.formulas,
  damage: attributes.damage,

  tierGrowthTenths: progression.tierGrowthTenths,
  peopleGrowthTenths: progression.peopleGrowthTenths,
  personalGrowthTenths: progression.personalGrowthTenths,
  personalGrowthMaxPerStat: progression.personalGrowthMaxPerStat,
  caps: progression.caps,
  accessoryCapOverflow: progression.accessoryCapOverflow,
  adaptationCap: progression.adaptationCap,
  promotionBonus: progression.promotionBonus,
  promotionGrades: progression.promotionGrades,
  rankCp: progression.rankCp,
  maxRank: progression.maxRank,
  rankProficiency: progression.rankProficiency,
  skillRanks: progression.skillRanks,
  rankAttributeBonusRanks: progression.rankAttributeBonusRanks,
  secondaryActionMinRank: progression.secondaryActionMinRank,
  proficiencies: progression.proficiencies,
  proficiencyIds: progression.proficiencyIds,
  proficiencyGrades: progression.proficiencyGrades,
  weaponTierGates: progression.weaponTierGates,
  xp: progression.xp,
  cp: progression.cp,
  commissions: progression.commissions,
  tierGates: progression.tierGates,
  loadout: progression.loadout,
  classTypes: progression.classTypes,
  defaultMove: progression.defaultMove,
  recruitment: progression.recruitment,
  deployment: progression.deployment,
  bonds: progression.bonds,
  deathRules: progression.deathRules,
  defaultDeathRule: progression.defaultDeathRule,

  modes: combat.modes,
  skillTypes: combat.skillTypes,
  elements: combat.elements,
  attackBases: combat.attackBases,
  mightSources: combat.mightSources,
  defenses: combat.defenses,
  elementMultipliers: combat.elementMultipliers,
  triangle: combat.triangle,
  effectiveness: combat.effectiveness,
  war: combat.war,
  terrain: combat.terrain,
  dungeon: combat.dungeon,
  delay: combat.delay,
  dungeonActions: combat.dungeonActions,
  warActions: combat.warActions,
  collapse: combat.collapse,
  statuses: combat.statuses,
  reactions: combat.reactions,

  overcast: resources.overcast,
  channel: resources.channel,
  matter: resources.matter,
  catalysts: resources.catalysts,
  studentTruthMultiplier: resources.studentTruthMultiplier,
  saturation: resources.saturation,
  divineAttention: resources.divineAttention,
  staticCharge: resources.staticCharge,
  stolenSlots: resources.stolenSlots,
  manaburn: resources.manaburn,
  rest: resources.rest,
  factions: resources.factions,
  standing: resources.standing,

  slots: equipment.slots,
  ppCosts: equipment.ppCosts,
  ppRefunds: equipment.ppRefunds,
  tiers: equipment.tiers,
  tierOrder: equipment.tierOrder,
  minimumPrice: equipment.minimumPrice,
  weaponGenerator: equipment.weaponGenerator,
  martialLines: equipment.martialLines,
  casterLines: equipment.casterLines,
  sidearmLines: equipment.sidearmLines,
  slayerMultiplier: equipment.slayerMultiplier,
  prefixShops: equipment.prefixShops,
  burden: equipment.burden,
  armor: equipment.armor,
  offhand: equipment.offhand,
  accessories: equipment.accessories,
  accessoryNames: equipment.accessoryNames,
  consumables: equipment.consumables,
  consumableNames: equipment.consumableNames,
  supplies: equipment.supplies,
  arts: equipment.arts,
  artDefaultWeight: equipment.artDefaultWeight,
  named: equipment.named,

  company: strategic.company,
  companyTypes: strategic.companyTypes,
  doctrines: strategic.doctrines,
  nationTracks: strategic.nationTracks,
  trackRange: strategic.trackRange,
  nationFormulas: strategic.nationFormulas,
  weaponsTrackUnlocks: strategic.weaponsTrackUnlocks,
  offweiss: strategic.offweiss,
  payouts: strategic.payouts,
  warClock: strategic.warClock,
  ships: strategic.ships,
  naval: strategic.naval,
  pacing: strategic.pacing,
  economy: strategic.economy,

  benchmarks: enemies.benchmarks,
  enemyFormulas: enemies.enemyFormulas,
  difficulty: enemies.difficulty,
  bossDifficultyRows: enemies.bossDifficultyRows,
  bossLevelGap: enemies.bossLevelGap,
  monsterTags: enemies.monsterTags
};

export default DEICIDE;
