import {writeFileSync} from "node:fs";
import {join} from "node:path";
import {ROOT, stableId} from "./lib/sources.mjs";
import {scenes} from "./content/scenes.mjs";

const T = 100;
const out = [];
for ( const scene of scenes ) {
  const levelIds = Object.fromEntries(scene.levels.map(level => [level.id, stableId("level", `${scene.id}:${level.id}`)]));
  const levels = scene.levels.map((level, index) => ({
    _id: levelIds[level.id], name: level.name, elevation: level.elevation,
    background: {color: level.color, src: null, tint: "#ffffff", alphaThreshold: 0.75},
    foreground: {src: null, tint: "#ffffff", alphaThreshold: 0.75}, fog: {src: null},
    textures: {anchorX: 0.5, anchorY: 0.5, offsetX: 0, offsetY: 0, fit: "fill", scaleX: 1, scaleY: 1, rotation: 0},
    visibility: {levels: []}, sort: (index + 1) * 100000, flags: {}
  }));
  const regions = scene.regions.map((region, index) => {
    const behaviors = [];
    if ( region.terrain ) {
      behaviors.push({
        _id: stableId("behavior", `${scene.id}:${region.id}:terrain`), name: "Deicide terrain", type: "terrain", disabled: false,
        system: {terrain: region.terrain.terrain, avoid: null, moveCost: null, matter: region.terrain.matter ?? null, plagueZone: Boolean(region.terrain.plagueZone), elevation: 0}, flags: {}
      });
    }
    if ( region.changeLevel ) {
      behaviors.push({_id: stableId("behavior", `${scene.id}:${region.id}:changeLevel`), name: "Change level", type: "changeLevel", disabled: false, system: {movementActions: ["walk", "climb", "crawl"]}, flags: {}});
    }
    return {
      _id: stableId("region", `${scene.id}:${region.id}`), name: region.name, color: region.color, shapes: region.shapes,
      elevation: {bottom: null, top: null, topInclusive: false}, levels: [levelIds[region.level]],
      restriction: {enabled: false, type: "move", priority: 0}, attachment: {token: null},
      behaviors, visibility: 0, highlightMode: "shapes", displayMeasurements: false, hidden: false, locked: false, sort: index, flags: {}
    };
  });
  const [w, h] = scene.size;
  out.push({
    name: scene.name, navigation: true,
    width: w * T, height: h * T, padding: 0.1,
    grid: {type: 1, size: T, style: "solidLines", thickness: 1, color: "#000000", alpha: 0.2, distance: 1, units: "tile"},
    backgroundColor: scene.backgroundColor,
    tokenVision: scene.fog, fog: {exploration: scene.fog},
    initialLevel: levelIds[scene.levels[0].id], levels, regions,
    flags: {deicide: {generated: true, identifier: scene.id, mode: scene.mode, fog: scene.fog}}
  });
  console.log(`${scene.name}: ${levels.length} levels, ${regions.length} regions, ${regions.reduce((n, r) => n + r.behaviors.length, 0)} behaviors`);
}
const file = join(ROOT, "module", "content", "scenes.mjs");
writeFileSync(file, `/**\n * Generated by tools/build-scenes.mjs from tools/content/scenes.mjs. Do not edit.\n */\nexport const SCENES = ${JSON.stringify(out)};\n`, "utf8");
console.log(`scenes ${out.length} written to module/content/scenes.mjs`);
