import {createHash} from "node:crypto";
import {mkdirSync, writeFileSync} from "node:fs";
import {join} from "node:path";
import {PACKS, ROOT, readSources, toCatalogEntry} from "./lib/sources.mjs";

const entries = [];
for ( const pack of PACKS ) {
  if ( !pack.catalog ) continue;
  for ( const doc of readSources(pack.folder) ) {
    const entry = toCatalogEntry(doc);
    if ( !entry ) continue;
    entry.uuid = `Compendium.deicide.${pack.name}.${pack.type}.${doc._id}`;
    entries.push(entry);
  }
}

const json = JSON.stringify(entries);
const hash = createHash("sha1").update(json).digest("hex").slice(0, 12);
const output = `/**
 * GENERATED by tools/build-catalog.mjs from packs-src. Do not hand edit. Run "npm run build:catalog".
 * ${entries.length} entries. Source hash ${hash}.
 */
export const HASH = "${hash}";
export const ENTRIES = ${json};
export default ENTRIES;
`;
mkdirSync(join(ROOT, "module", "content"), {recursive: true});
writeFileSync(join(ROOT, "module", "content", "builtin.mjs"), output, "utf8");
console.log(`Catalog: ${entries.length} entries, hash ${hash}`);
